name: m4-parks-be
on:
  pull_request:
    branches: [ci_test_base, main]
  push:
    branches: [ci_test_base, main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password

    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          # ruby-version: 3.2.2
      - name: Install Gems
        run: |
          bundle install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run RSpec Tests
        run: bundle exec rspec

      # - name: Setup Database
      #   env:
      #     RAILS_ENV: test
      #     RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      #     # POSTGRES_DATABASE: postgres
      #     POSTGRES_HOST: localhost
      #     POSTGRES_USER: postgres
      #     POSTGRES_PASSWORD: postgres
      #   run: |
      #     bin/rails db:create
      #     bin/rails db:schema:load


      # - name: Deploy
      #   # Only run this step if the branch is main
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl "$deploy_url"
  #comment