name: m4-parks-be
on:
  pull_request:
  push:
    branches: [ci_test_base, main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_DATABASE: postgres
          POSTGRES_HOST: localhost
        run: |
          sudo systemctl start postgresql.service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install Gems
        run: |
          bundle install

      - name: Setup Database
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_DATABASE: postgres
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          bin/rails db:create
          bin/rails db:schema:load

      - name: Run RSpec Tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          PPOSTGRES_DATABASE: postgres
          PPOSTGRES_HOST: localhost
          PPOSTGRES_USER: postgres
          PPOSTGRES_PASSWORD: postgres
        run: bundle exec rspec

      # - name: Deploy
      #   # Only run this step if the branch is main
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl "$deploy_url"
